version: "3"
services:
  bind:
    build: ./bind
    image: dyndns-bind
    container_name: bind
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - "bind-config:/etc/bind/"
      - "certbot-config:/etc/certbot/"
    environment:
      - ZONE=dyndns.dappnode.io
      - UPDATE_HOST=172.18.0.0/16
      - KEY_NAME=certbot
      - KEY_PATH="/etc/certbot/certbot.key"
    restart: always

  dyndns-api:
    image: dyndns-api
    build: ./api
    container_name: dyndns-api
    expose:
      - 8080
    environment:
      - VIRTUAL_HOST=ns.dappnode.io
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=ns.dappnode.io
      - LETSENCRYPT_EMAIL=community@dappnode.io
      - DYNDNS_BIND_SERVER=bind
      - DYNDNS_ZONE=dyndns.dappnode.io
      - DYNDNS_THRESHOLD=600
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "nginx-config:/etc/nginx/conf.d"
      - "nginx-certs:/etc/nginx/certs"
      - "nginx-vhosts:/etc/nginx/vhost.d"
      - "nginx-webroot:/usr/share/nginx/html"
    restart: always

  dockergen:
    image: jwilder/docker-gen
    container_name: nginx-docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - "nginx-config:/etc/nginx/conf.d"
      - "nginx-certs:/etc/nginx/certs"
      - "nginx-vhosts:/etc/nginx/vhost.d"
      - "nginx-webroot:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro"
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-docker-gen
      NGINX_PROXY_CONTAINER: nginx
    volumes:
      - "nginx-config:/etc/nginx/conf.d"
      - "nginx-certs:/etc/nginx/certs"
      - "nginx-vhosts:/etc/nginx/vhost.d"
      - "nginx-webroot:/usr/share/nginx/html"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: always

volumes:
  bind-config:
  certbot-config:
  nginx-config:
  nginx-certs:
  nginx-vhosts:
  nginx-webroot:

networks:
  default:
    external:
      name: nginx-proxy
