version: '3'
services:
  bind:
    restart: always
    build: ./bind
    image: dyndns-bind
    container_name: bind
    ports:
      - "53:53"
      - "53:53/udp"
    volumes:
      - 'bind-config:/etc/bind/'
    environment:
      - ZONE=dyn.dappnode.io
      - UPDATE_HOST=172.18.0.0/16

  dyndns-api:
    restart: always
    image: dyndns-api
    build: ./api
    container_name: dyndns-api
    expose:
      - 8080
    environment:
      - VIRTUAL_HOST=ns.dappnode.io
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=ns.dappnode.io
      - LETSENCRYPT_EMAIL=email@dappnode.io
      - DYNDNS_BIND_SERVER=bind
      - DYNDNS_ZONE=dyn.dappnode.io
      - DYNDNS_THRESHOLD=600

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'nginx-config:/etc/nginx/conf.d'
      - 'nginx-certs:/etc/nginx/certs'
      - 'nginx-vhosts:/etc/nginx/vhost.d'
      - 'nginx-webroot:/usr/share/nginx/html'

  dockergen:
    image: jwilder/docker-gen
    container_name: nginx-docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - 'nginx-config:/etc/nginx/conf.d'
      - 'nginx-certs:/etc/nginx/certs'
      - 'nginx-vhosts:/etc/nginx/vhost.d'
      - 'nginx-webroot:/usr/share/nginx/html'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro'

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-docker-gen
      NGINX_PROXY_CONTAINER: nginx
    volumes:
      - 'nginx-config:/etc/nginx/conf.d'
      - 'nginx-certs:/etc/nginx/certs'
      - 'nginx-vhosts:/etc/nginx/vhost.d'
      - 'nginx-webroot:/usr/share/nginx/html'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'

volumes:
  nginx-config:
  nginx-certs:
  nginx-vhosts:
  nginx-webroot:

networks:
  default:
    external:
      name: nginx-proxy
